force-app/main/default/objects/Territory_ID__c/Territory_ID__c.object-meta.xml
<CustomObject>
    <label>TerritoryID</label>
    <nameField>
        <label>TerritoryID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerritoryIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_ID__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</description>
    <inlineHelpText>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</inlineHelpText>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>TerritoryIDs</relationshipLabel>
    <relationshipName>TerritoryIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/TerritoryName__c.object-meta.xml
<CustomObject>
    <label>Territory Name</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryName__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TerritoryID_u.cls
public with sharing class TerritoryID_u {
    
    List<String> tidFields = Utility.FieldNames('Territory_ID__c');
    List<String> tnFields = Utility.FieldNames('TerritoryName__c');
    public Territory_ID__c theTid = new Territory_ID__c();
    String query = 'Select ';
    String subquery = '(Select Id, Owner from Accounts)';
    Integer i = 0;    
    
    //building a dynamic query of all the fields in the Territory Id object given a trigger record
    //used when you have to do a before insert context on the same record
    public TerritoryID_u(Territory_ID__c tid){
        id tidid = tid.Id;
        for(String tidField : tidFields){
            if(i < tidFields.size()){
                query += tidField + ', ';
            } else query += tidfield;
            i += 1;
        }
        
        //reset for related object Territory_Name__r fields
        i=1;
        for(String tnField : tnFields){
            if(i < tnFields.size()){
                query += 'Territory_Name__r.' + tnField + ', ';
            } else query += 'Territory_Name__r.' + tnField;
            i += 1;
        }
        //query += subquery;
        query += ' from Territory_ID__c where Id = :tidid';
        
        system.debug('the TID query is ' + query);
        theTid = Database.query(query);
    }
}