force-app/main/default/objects/Account/fields/AMUser__c.field-meta.xml
<CustomField>
    <fullName>AMUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_AM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PCUser__c.field-meta.xml
<CustomField>
    <fullName>PCUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_PC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RVPUser__c.field-meta.xml
<CustomField>
    <fullName>RVPUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_RVP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Special_Territory_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Special_Territory_Assignment__c</fullName>
    <label>Special Territory Assignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMETEK</fullName>
            </value>
            <value>
                <fullName>School for the Deaf</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TerritoryOverride__c.field-meta.xml
<CustomField>
    <fullName>TerritoryOverride__c</fullName>
    <inlineHelpText>Overrides the Territory Assignment rules and allows you to set the value yourself. Select &quot;Override by ID&quot;, then enter a value in Territory ID field and the rest of the fields will be populated automatically. To bypass all territory and enter all of the values manually choose &quot;Manual Input&quot; value.</inlineHelpText>
    <label>Territory Override</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Override by ID</fullName>
            </value>
            <value>
                <fullName>Manual Input</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_ID__c/Territory_ID__c.object-meta.xml
<CustomObject>
    <label>TerritoryID</label>
    <nameField>
        <label>TerritoryID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerritoryIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_ID__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</description>
    <inlineHelpText>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</inlineHelpText>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>TerritoryIDs</relationshipLabel>
    <relationshipName>TerritoryIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public class AccountTriggerHandler {
    /* Updated 2022-03-01 Bob Phelps to only fire when necessary to make the assignment changes
     */
    public static Boolean bypassTrigger = false;
    
    public AccountTriggerHandler() {}
    
    public void run() {
        if (bypassTrigger == true) {
            return;
        }

        if (Trigger.isBefore && Trigger.isInsert) {
            assignCustomTerritories(Trigger.new);
            AccountUtility.setParentAccounts(Trigger.new);
        }
        else if (Trigger.isBefore && Trigger.isUpdate) {
            ownerChanged(Trigger.new, (Map<Id, Account>)Trigger.oldMap);//changed to call method to determine if the account owner changed on the trigger records
            AccountUtility.setParentAccountsOnUpdate(Trigger.new, (Map<Id, Account>)Trigger.oldMap);
        }
        else if (Trigger.isAfter && Trigger.isUpdate) {
            // reevaluateOpportunityTerritoryFilter();
        }
    }
    
    public static void ownerChanged(List<Account> accts, Map<Id, Account> oldMap){
        //on an update, only want to call assignCustomTerritories if the owner of the account changes
        List<Account> ownerChangedAccounts = new List<Account>();
        for(Account acct:accts){
            if(acct.OwnerId != oldMap.get(acct.Id).OwnerId){
                ownerChangedAccounts.add(acct);
            }
        }
        if(ownerChangedAccounts != null && ownerChangedAccounts.size() > 0 && !ownerChangedAccounts.isempty()){
            assignCustomTerritories(ownerChangedAccounts);
        }
    }

    public static List<Account> assignCustomTerritories(List<Account> accounts) {
        Set<String> postalCodes = new Set<String>();
        List<Account> accList = new List<Account>();
        Map<Id, String> overrideMap = new Map<Id, String>();
        for (Account acc: accounts) {
            if (acc.TerritoryOverride__c == 'Override by ID') {
            	postalCodes.add(acc.ShippingPostalCode);
            	accList.add(acc);
                overrideMap.put(acc.Id, acc.Territory_ID__c);
            } else if (String.isBlank(acc.TerritoryOverride__c)) {
            	postalCodes.add(acc.ShippingPostalCode);
            	accList.add(acc);
            }
        }
        // Collect accounts with modified owners
        Map<Id, Account> accMap = new Map<Id, Account>();
        TerritoryAssignmentHandler handler = new TerritoryAssignmentHandler(postalCodes, 'Account', overrideMap);
        for (Account acc: accList) {
            TerritoryAssignmentHandler.TerritoryStruct territoryDetails = handler.getTerritoryDetails(acc.Id, acc.ShippingPostalCode, acc.Special_Territory_Assignment__c);
            acc.Territory_ID__c = territoryDetails.territoryNumber;
            acc.Territory_Name__c = territoryDetails.territoryId;
            acc.AM__c = territoryDetails.am;
            acc.AMUser__c = territoryDetails.amId;
            acc.RVP__c = territoryDetails.rvp;
            acc.RVPUser__c = territoryDetails.rvpId;
            acc.PC__c = territoryDetails.pc;
            acc.PCUser__c = territoryDetails.pcId;
            acc.State__c = territoryDetails.state;
            acc.County__c = territoryDetails.county;

            if (!String.isBlank(territoryDetails.amId)) {
                acc.OwnerId = territoryDetails.amId;
                accMap.put(acc.Id, acc);
            }
        }
        // Update the Owners of related open Opportunities and Contacts
		OpportunityUtility.setRelatedOpenOpportunityOwner(accMap);
        ContactUtility.setRelatedContactOwner(accMap);
        return accList;
    }
}