force-app/main/default/objects/Account/fields/ncessch__c.field-meta.xml
<CustomField>
    <fullName>ncessch__c</fullName>
    <description>NCES School Code</description>
    <externalId>true</externalId>
    <inlineHelpText>NCES School Code</inlineHelpText>
    <label>NCES Public School ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/No_NCES_Data__c.field-meta.xml
<CustomField>
    <fullName>No_NCES_Data__c</fullName>
    <label>No NCES Data</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Not Found</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ParentNcesId__c.field-meta.xml
<CustomField>
    <fullName>ParentNcesId__c</fullName>
    <description>NCES ID of the parent district.</description>
    <label>Parent NCES ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>true</active>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Contact/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <formula>Account.County_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>County</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
                <isActive>false</isActive>
                <label>Contact</label>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
                <isActive>false</isActive>
                <label>Not Qualified</label>
            </value>
            <value>
                <fullName>Pipeline</fullName>
                <isActive>false</isActive>
                <label>Pipeline</label>
            </value>
            <value>
                <fullName>Pre-Pipeline</fullName>
                <isActive>false</isActive>
                <label>Pre-Pipeline</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <formula>Account.Territory_ID__c</formula>
    <label>Territory ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains a lookup to account for the purpose of picking a bill to address</description>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confidence_Level__c.field-meta.xml
<CustomField>
    <fullName>Confidence_Level__c</fullName>
    <label>Confidence Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>Expected</fullName>
            </value>
            <value>
                <fullName>Possible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is a lookup to the Account object for the destination address</description>
    <label>Destination</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Destination)</relationshipLabel>
    <relationshipName>Opportunities_destination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Source__c.field-meta.xml
<CustomField>
    <fullName>Interest_Source__c</fullName>
    <label>Interest Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advisory board</fullName>
            </value>
            <value>
                <fullName>ARC summit event</fullName>
            </value>
            <value>
                <fullName>Colloquium</fullName>
            </value>
            <value>
                <fullName>Conference Booth/networking</fullName>
            </value>
            <value>
                <fullName>Ed Reports</fullName>
            </value>
            <value>
                <fullName>Existing relationship</fullName>
            </value>
            <value>
                <fullName>IRLA/ENIL demo</fullName>
            </value>
            <value>
                <fullName>National email blast</fullName>
            </value>
            <value>
                <fullName>Personal email</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>RFP</fullName>
            </value>
            <value>
                <fullName>Seeing is believing</fullName>
            </value>
            <value>
                <fullName>Territory E-blast</fullName>
            </value>
            <value>
                <fullName>Web lead</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Push In Placeholder</fullName>
                <isActive>false</isActive>
                <label>Push In Placeholder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the account object for purpose of picking a ship to address</description>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To)</relationshipLabel>
    <relationshipName>Opportunities_ship_to</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <formula>Account.Territory_ID__c</formula>
    <label>Territory ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory_ID__c/Territory_ID__c.object-meta.xml
<CustomObject>
    <label>TerritoryID</label>
    <nameField>
        <label>TerritoryID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerritoryIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_ID__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <externalId>true</externalId>
    <label>Zip Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTerritoryTriggerTest.cls
@isTest
public class AccountTerritoryTriggerTest {

    @isTest
    public static void m1()
    {
        Territory_ID__c  territory = new Territory_ID__c();
        territory.City__c = 'test';
        territory.County__c = 'test';
        territory.Name = 'qwerty';
        territory.Zip_Code__c = '12345';
        territory.County__c = 'wqerty';
        insert territory;
        
        Account acc1 = new Account(Name='parent 1',ParentNcesId__c='12345678');
        Account acc2 = new Account(Name='parent2',ParentNcesId__c='123456789');
        
        Account acc = new Account();
        acc.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'School'].Id;
        acc.Name = 'testing';
        acc.ShippingPostalCode = '12345';
        acc.ncessch__c = '000001';
        acc.Status__c = 'Active';
		acc.No_NCES_Data__c = 'Not Found';
        acc.ParentNcesId__c='12345678';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'test';
        opp.StageName = 'Target';
        opp.Confidence_Level__c = 'Yes';
        opp.CloseDate = Date.today();
        opp.AccountId = acc.id;
        opp.Ship_To__c = acc.Id;
        opp.Bill_To__c = acc.Id;
        opp.Destination__c = acc.Id;
        opp.Interest_Source__c = 'Advisory board';
        insert opp;
        
        Case cs = new Case();cs.AccountId = acc.Id;
        //insert cs;
        
        Contact con = new Contact();
        con.FirstName = 'test';
        con.LastName = 'tests';
        con.email = 'test@gmail.com';
        con.AccountId = acc.id;
        insert con;
        
        Task tsk = new Task();
        tsk.WhatId = acc.Id;
        tsk.Subject = 'Call';
        insert tsk;
        
        Event et = new Event();
        et.WhatId = acc.Id;
        et.DurationInMinutes = 120;
        et.ActivityDateTime = DateTime.now();
        et.Subject = 'Meeting';
        insert et;
        
        acc.ParentNcesId__c='123456789';
        acc.name= 'test';
        update acc;
    }
}