force-app/main/default/objects/Account/fields/ncesleaid__c.field-meta.xml
<CustomField>
    <fullName>ncesleaid__c</fullName>
    <description>NCES District Code</description>
    <externalId>true</externalId>
    <inlineHelpText>NCES District Code</inlineHelpText>
    <label>NCES District ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ncessch__c.field-meta.xml
<CustomField>
    <fullName>ncessch__c</fullName>
    <description>NCES School Code</description>
    <externalId>true</externalId>
    <inlineHelpText>NCES School Code</inlineHelpText>
    <label>NCES Public School ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ParentAccountTEST__c.field-meta.xml
<CustomField>
    <fullName>ParentAccountTEST__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account (TEST)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Accounts (TEST)</relationshipLabel>
    <relationshipName>ChildAccountsTest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ParentNcesId__c.field-meta.xml
<CustomField>
    <fullName>ParentNcesId__c</fullName>
    <description>NCES ID of the parent district.</description>
    <label>Parent NCES ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TerritoryOverride__c.field-meta.xml
<CustomField>
    <fullName>TerritoryOverride__c</fullName>
    <inlineHelpText>Overrides the Territory Assignment rules and allows you to set the value yourself. Select &quot;Override by ID&quot;, then enter a value in Territory ID field and the rest of the fields will be populated automatically. To bypass all territory and enter all of the values manually choose &quot;Manual Input&quot; value.</inlineHelpText>
    <label>Territory Override</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Override by ID</fullName>
            </value>
            <value>
                <fullName>Manual Input</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/District.recordType-meta.xml
<RecordType>
    <fullName>District</fullName>
    <active>true</active>
    <label>District</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>true</active>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AM__c.field-meta.xml
<CustomField>
    <fullName>AM__c</fullName>
    <formula>Account.AM__c</formula>
    <label>AM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <formula>Account.County_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>County</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PC__c.field-meta.xml
<CustomField>
    <fullName>PC__c</fullName>
    <formula>Account.PC__c</formula>
    <label>PC</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RVP__c.field-meta.xml
<CustomField>
    <fullName>RVP__c</fullName>
    <formula>Account.RVP__c</formula>
    <label>RVP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Account.State__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Territory State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
                <isActive>false</isActive>
                <label>Contact</label>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
                <isActive>false</isActive>
                <label>Not Qualified</label>
            </value>
            <value>
                <fullName>Pipeline</fullName>
                <isActive>false</isActive>
                <label>Pipeline</label>
            </value>
            <value>
                <fullName>Pre-Pipeline</fullName>
                <isActive>false</isActive>
                <label>Pre-Pipeline</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <formula>Account.Territory_ID__c</formula>
    <label>Territory ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <formula>Account.Territory_Name__r.Name</formula>
    <label>Territory Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AM__c.field-meta.xml
<CustomField>
    <fullName>AM__c</fullName>
    <formula>Account.AM__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confidence_Level__c.field-meta.xml
<CustomField>
    <fullName>Confidence_Level__c</fullName>
    <label>Confidence Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Firm</fullName>
            </value>
            <value>
                <fullName>Expected</fullName>
            </value>
            <value>
                <fullName>Possible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PC__c.field-meta.xml
<CustomField>
    <fullName>PC__c</fullName>
    <formula>Account.PC__c</formula>
    <label>PC</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RVP__c.field-meta.xml
<CustomField>
    <fullName>RVP__c</fullName>
    <formula>Account.RVP__c</formula>
    <label>RVP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <formula>Account.Territory_ID__c</formula>
    <label>Territory ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <formula>Account.Territory_Name__r.Name</formula>
    <label>Territory Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sales_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Sales_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sales_Opportunity</businessProcess>
    <description>Opportunity Type for Standard ARC Products</description>
    <label>Sales Opportunity</label>
</RecordType>

force-app/main/default/objects/ParentAccountAssignmentSetting__mdt/ParentAccountAssignmentSetting__mdt.object-meta.xml
<CustomObject>
    <label>Parent Account Assignment Setting</label>
    <pluralLabel>Parent Account Assignment Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ParentAccountAssignmentSetting__mdt/fields/ParentField__c.field-meta.xml
<CustomField>
    <fullName>ParentField__c</fullName>
    <label>Parent Field</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ParentId</fullName>
                <label>Parent Account</label>
            </value>
            <value>
                <fullName>ParentAccountTEST__c</fullName>
                <default>true</default>
                <label>Parent Account (TEST)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_ID__c/Territory_ID__c.object-meta.xml
<CustomObject>
    <label>TerritoryID</label>
    <nameField>
        <label>TerritoryID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerritoryIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_ID__c/fields/StateAbbr__c.field-meta.xml
<CustomField>
    <fullName>StateAbbr__c</fullName>
    <label>StateAbbr</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory_ID__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</description>
    <inlineHelpText>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</inlineHelpText>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>TerritoryIDs</relationshipLabel>
    <relationshipName>TerritoryIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/TerritoryName__c.object-meta.xml
<CustomObject>
    <label>Territory Name</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryName__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TerritoryAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTriggerTest.cls
@isTest
public class AccountTriggerTest {
    
    @isTest
    private static void beforeInsertTerritoryAssignment() {
        Account acc = TestFactory.createSchoolAccount('12345');
        List<String> zipCodes = new List<String>();
        zipCodes.add(acc.ShippingPostalCode);

        String territoryId = '99';
        List<Territory_ID__c> territories = TestFactory.createTerritories(territoryId, zipCodes);
        insert territories;
        List<TerritoryName__c> positions = new List<TerritoryName__c>();
        TerritoryName__c am = TestFactory.createAccountManager('Lincoln Turner', territoryId);
		positions.add(am);
        TerritoryName__c rvp = TestFactory.createRegionalVicePresident('John Appleseed', territoryId);
		positions.add(rvp);
        TerritoryName__c pc = TestFactory.createProgramConsultant('Cathy Smith', territoryId);
        positions.add(pc);
        insert positions;
        
        
        Test.startTest();
        	insert acc;
        Test.stopTest();
        
        Account updatedAcc = [SELECT Id, Territory_Name__c, Territory_ID__c, AM__c, PC__c, RVP__c, State__c, County__c, OwnerId FROM Account WHERE Id = :acc.Id];
        System.assertEquals(am.Id, updatedAcc.Territory_Name__c);
        System.assertEquals(territoryId, updatedAcc.Territory_ID__c);
        System.assertEquals(am.Name, updatedAcc.AM__c);
        System.assertEquals(pc.Name, updatedAcc.PC__C);
        System.assertEquals(rvp.Name, updatedAcc.RVP__C);
        System.assertEquals(territories[0].StateAbbr__c, updatedAcc.State__c);
        System.assertEquals(territories[0].County__c, updatedAcc.County__c);
        System.assertEquals(am.User__c, updatedAcc.OwnerId);
    }

    @isTest
    private static void beforeInsertTerritoryAssignmentOverride() {
        Account acc = TestFactory.createSchoolAccount(null);
        acc.TerritoryOverride__c = 'Override by ID';
        acc.Territory_ID__c = '99';
        List<String> zipCodes = new List<String>();
        zipCodes.add(acc.ShippingPostalCode);

        String territoryId = '99';
        List<Territory_ID__c> territories = TestFactory.createTerritories(territoryId, zipCodes);
        insert territories;
        List<TerritoryName__c> positions = new List<TerritoryName__c>();
        TerritoryName__c am = TestFactory.createAccountManager('Lincoln Turner', territoryId);
		positions.add(am);
        TerritoryName__c rvp = TestFactory.createRegionalVicePresident('John Appleseed', territoryId);
		positions.add(rvp);
        TerritoryName__c pc = TestFactory.createProgramConsultant('Cathy Smith', territoryId);
        positions.add(pc);
        insert positions;
        
        
        Test.startTest();
        	insert acc;
        Test.stopTest();
        
        Account updatedAcc = [SELECT Id, Territory_Name__c, Territory_ID__c, AM__c, PC__c, RVP__c, State__c, County__c, ShippingPostalCode, OwnerId FROM Account WHERE Id = :acc.Id];
        System.assertEquals(null, updatedAcc.ShippingPostalCode);
        System.assertEquals(am.Id, updatedAcc.Territory_Name__c);
        System.assertEquals(territoryId, updatedAcc.Territory_ID__c);
        System.assertEquals(am.Name, updatedAcc.AM__c);
        System.assertEquals(pc.Name, updatedAcc.PC__C);
        System.assertEquals(rvp.Name, updatedAcc.RVP__C);
        System.assertEquals(territories[0].StateAbbr__c, updatedAcc.State__c);
        System.assertEquals(territories[0].County__c, updatedAcc.County__c);
        System.assertEquals(am.User__c, updatedAcc.OwnerId);
    }

    @isTest
    public static void beforeInsertSetParentAccountByNCESID() {
        Account district = TestFactory.createDistrictAccount('09876');
        district.ncesleaid__c = 'NCES09876';
        insert district;
        
        Account school = TestFactory.createSchoolAccount('12345');
        school.ParentNcesId__c = 'NCES09876';

		System.assertEquals(null, school.ParentAccountTEST__c);
        Test.startTest();
        	insert school;
        Test.stopTest();
        ParentAccountAssignmentSetting__mdt setting = [SELECT Id, ParentField__c FROM ParentAccountAssignmentSetting__mdt LIMIT 1];
        Account updatedSchool = [SELECT Id, ParentAccountTEST__c, ParentId FROM Account WHERE Id = :school.Id];
        System.assertEquals(district.Id, updatedSchool.get(setting.ParentField__c));
    }
    
    @isTest
    public static void beforeUpdateSetParentAccountByNCESID() {
        AccountTriggerHandler.bypassTrigger = true;
            Account district = TestFactory.createDistrictAccount('09876');
            district.ncesleaid__c = 'NCES09876';
            insert district;
        AccountTriggerHandler.bypassTrigger = false;
        
        Account school = TestFactory.createSchoolAccount('12345');
        insert school;

        Account updatedSchool = [SELECT Id, ParentAccountTEST__c, ParentId FROM Account WHERE Id = :school.Id];
		System.assertEquals(null, school.ParentAccountTEST__c);
        Test.startTest();
            school.ParentNcesId__c = 'NCES09876';
			update school;
        Test.stopTest();
        ParentAccountAssignmentSetting__mdt setting = [SELECT Id, ParentField__c FROM ParentAccountAssignmentSetting__mdt LIMIT 1];
        updatedSchool = [SELECT Id, ParentAccountTEST__c, ParentId FROM Account WHERE Id = :school.Id];
        System.assertEquals(district.Id, updatedSchool.get(setting.ParentField__c));
    }

    @isTest
    private static void beforeUpdateTerritoryAssignment() {
        Account acc = TestFactory.createSchoolAccount('12345');
        insert acc;
        Opportunity opp = TestFactory.createOpportunity(acc.Id);
        insert opp;
		Contact con = TestFactory.createContact(acc.Id);
        insert con;

        String territoryId = '99';
        List<String> zipCodes = new List<String>();
        zipCodes.add('98765');
        List<Territory_ID__c> territories = TestFactory.createTerritories(territoryId, zipCodes);
        insert territories;
        List<TerritoryName__c> positions = new List<TerritoryName__c>();
        TerritoryName__c am = TestFactory.createAccountManager('Lincoln Turner', territoryId);
		positions.add(am);
        TerritoryName__c rvp = TestFactory.createRegionalVicePresident('John Appleseed', territoryId);
		positions.add(rvp);
        TerritoryName__c pc = TestFactory.createProgramConsultant('Cathy Smith', territoryId);
        positions.add(pc);
        insert positions;

        Test.startTest();
        	acc.ShippingPostalCode = '98765';
        	update acc;
        Test.stopTest();
        
        Account updatedAcc = [SELECT Id, Territory_Name__c, Territory_ID__c, AM__c, PC__c, RVP__c, State__c, County__c, OwnerId FROM Account WHERE Id = :acc.Id];
        System.assertEquals(am.Id, updatedAcc.Territory_Name__c);
        System.assertEquals(territoryId, updatedAcc.Territory_ID__c);
        System.assertEquals(am.Name, updatedAcc.AM__c);
        System.assertEquals(pc.Name, updatedAcc.PC__C);
        System.assertEquals(rvp.Name, updatedAcc.RVP__C);
        System.assertEquals(territories[0].StateAbbr__c, updatedAcc.State__c);
        System.assertEquals(territories[0].County__c, updatedAcc.County__c);
        System.assertEquals(am.User__c, updatedAcc.OwnerId);
        
        Opportunity updatedOpp = [SELECT Id, OwnerId FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(am.User__c, updatedOpp.OwnerId);
        
        Contact updatedCon = [SELECT Id, OwnerId FROM Contact WHERE Id = :con.Id];
        System.assertEquals(am.User__c, updatedCon.OwnerId);
    }
    
/* OBSOLETE TESTS - TERRITORY HIERARCHY DISABLED 
    @isTest
    private static void afterUpdateOpportunityTerritoryUpdate() {
        // Get Active Territory Model
        Account acc = createInsertAccount();
        Opportunity opp = createInsertOpportunity(acc.Id);
        Territory2Model model = [SELECT Id FROM Territory2Model WHERE State = 'Active' LIMIT 1];
        List<ObjectTerritory2Association> existingAssociations = [SELECT Id FROM ObjectTerritory2Association WHERE ObjectId = :acc.Id];
        Territory2 ter = [SELECT Id FROM Territory2 WHERE Territory2ModelId = :model.Id LIMIT 1];
        ObjectTerritory2Association acc2territory = new ObjectTerritory2Association();
        acc2territory.ObjectId = acc.Id;
        acc2territory.Territory2Id = ter.Id;
        acc2territory.AssociationCause = 'Territory2Manual';
        insert acc2territory;

        opp = [SELECT Id, Territory2Id FROM Opportunity WHERE AccountId = :acc.Id LIMIT 1];
        System.assertNotEquals(ter.Id, opp.Territory2Id, 'Opportunity shall not have a territory');
        Test.startTest();
            acc.Name = 'Test Update';
            update acc;
        Test.stopTest();
        Opportunity updatedOpp = [SELECT Id, Territory2Id FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(ter.Id, updatedOpp.Territory2Id, 'Expected territory Id was not set');
    }

    private static Account createInsertAccount() {
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'School'].Id;
        acc.Status__c = 'Active';
        acc.ncessch__c = '00001';
        insert acc;
        return acc;
    }

    private static Opportunity createInsertOpportunity(Id accountId) {
        Opportunity opp = new Opportunity();
        opp.AccountId = accountId;
        opp.Name = 'Test Opportunity for School';
        opp.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'Sales_Opportunity'].Id;
        opp.IsExcludedFromTerritory2Filter = true;
        opp.StageName = 'Target';
        opp.CloseDate = System.today().addMonths(1);
        opp.Confidence_Level__c = 'yes';
        insert opp;
        return opp;
    }
*/
}