force-app/main/default/objects/Account/fields/Related_TerritoryID__c.field-meta.xml
<CustomField>
    <fullName>Related_TerritoryID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Forms a join relationship to the TerritoryID that this account is assigned to, which will in turn inherit the Territory that the TerritoryID is assigned to.</description>
    <inlineHelpText>Forms a join relationship to the TerritoryID that this account is assigned to, which will in turn inherit the Territory that the TerritoryID is assigned to.</inlineHelpText>
    <label>Related TerritoryID</label>
    <referenceTo>Territory_ID__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <formula>Account.Territory_Name__r.Name</formula>
    <label>Territory Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory_ID__c/Territory_ID__c.object-meta.xml
<CustomObject>
    <label>TerritoryID</label>
    <nameField>
        <label>TerritoryID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerritoryIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_ID__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</description>
    <inlineHelpText>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</inlineHelpText>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>TerritoryIDs</relationshipLabel>
    <relationshipName>TerritoryIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/TerritoryName__c.object-meta.xml
<CustomObject>
    <label>Territory Name</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunitiesUpdateBatch.cls
public class OpportunitiesUpdateBatch implements Database.Batchable<Sobject> {
    /* Author: Bob Phelps
     *
     *  Date Created: 03/28/2021
     *
     *  Purpose: Batch process to bulk update Opportunities
     *
     *  Notes:
     *
     *  Modification History:
     *  Date / Author  / Description
     *  -------------  ------------------  --------------------------------------------------------------------------------------------------------------
     * */

Set<Id> territoryNameIds;
    String amId;
    public OpportunitiesUpdateBatch(Set<Id> TNIds, String ownerid) {
        this.territoryNameIds = TNIds;
        this.amId = ownerid;
    }
    //get the list of opportunities
    public Database.QueryLocator start(Database.BatchableContext BC) {
         // collect the opportunities to be processed. this query ONLY collects those whose owners do NOT match
        // the new owner id being passed to the batch
        String query = 'Select Id, OwnerId from Opportunity where Account.Related_TerritoryID__r.Territory_Name__r.Id in: territoryNameIds and OwnerId != :amId and StageName != \'Closed Won\'';
        return Database.getQueryLocator(query);
    }
    //perform the update
    public void execute(Database.BatchableContext BC, List<Opportunity> opps) {
        if(Utility.isNullorEmpty(opps) == false){
        for (Opportunity opp : opps) {
            opp.OwnerId = amId;
        }
        DMLOperations dmlupdate = new DMLOperations(opps, 'update');
    }
    }

    //send the user an email with the batch results
    public void finish(Database.BatchableContext BC) {
        AsyncApexJob a = [
            SELECT Id, Status, ExtendedStatus, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :BC.getJobId()
        ];

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new List<String>{ a.CreatedBy.Email };
        mail.setToAddresses(toAddresses);
        mail.setSubject('Opportunity Owners Updated ' + a.Status);
        mail.setPlainTextBody('records processed ' + a.TotalJobItems + 'with ' + a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
    }
}