force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <formula>Account.Territory_ID__c</formula>
    <label>Territory ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <formula>Account.Territory_ID__c</formula>
    <label>Territory ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory_ID__c/Territory_ID__c.object-meta.xml
<CustomObject>
    <label>TerritoryID</label>
    <nameField>
        <label>TerritoryID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerritoryIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryName__c/TerritoryName__c.object-meta.xml
<CustomObject>
    <label>Territory Name</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryName__c/fields/Program_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Program_Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Regional Vice President assigned to this Territory. Added -03-2022 to consolidate Territory records</description>
    <inlineHelpText>The Regional Vice President assigned to this Territory</inlineHelpText>
    <label>Program Consultant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Names1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/fields/Regional_VP__c.field-meta.xml
<CustomField>
    <fullName>Regional_VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Regional Vice President assigned to this Territory. Added 03-2022 to consolidate Territory records</description>
    <inlineHelpText>The Regional Vice President assigned to this Territory</inlineHelpText>
    <label>Regional VP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Names</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TerritoryAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TerritoryName_t.cls
@isTest
public class TerritoryName_t {
//test class for the TerritoryName__c object
        
    //test to ensure that if the AM on the Territory Name object is changed then
    //all the Accounts, Contacts and Opps assocaited with the Territory Name 
    //should change their owners to the new AM.
    @isTest
    public static void afterupdateuser(){
        Set<String> usernames = Utility.generateusernames(3);
        List<User> users = TestFactory.CreateUser(usernames);
        List<TerritoryName__c> territorynames = TestFactory.createTerritoryNames(5, users);
        List<String> zipcodes = Utility.generatezipcodes(5);
        List<Territory_ID__c> territories = TestFactory.createTerritories(zipCodes, territorynames);
        List<Account> accts = TestFactory.createSchoolAccounts(zipcodes);
        List<Contact> contacts = TestFactory.createContacts(accts);
        List<Opportunity> opps = TestFactory.createOpportunities(accts);
        
        Test.startTest();
        territorynames[0].User__c = users[1].Id;
        update territorynames;
        Test.stopTest();
        //because this calls an asynchronous batch jobs can't do asserts
    }
    
    //test to ensure that if the PC or the RVP are changed on a Territory Name, then the associated
    //Accounts have their Account Teams inserted as well
    @isTest
    public static void afterupdateteaminsert(){
        Set<String> usernames = Utility.generateusernames(3);
        List<User> users = TestFactory.CreateUser(usernames);
        List<TerritoryName__c> territorynames = TestFactory.createTerritoryNames(5, users);
        List<String> zipcodes = Utility.generatezipcodes(5);
        List<Territory_ID__c> territories = TestFactory.createTerritories(zipCodes, territorynames);
        List<Account> accts = TestFactory.createSchoolAccounts(zipcodes);
        List<Contact> contacts = TestFactory.createContacts(accts);
        List<Opportunity> opps = TestFactory.createOpportunities(accts);
        
        Test.startTest();
        territorynames[0].Program_Consultant__c = users[0].Id;
        territorynames[0].Regional_VP__c = users[1].Id;
        update territorynames;
        Test.stopTest();
        //because this calls an asynchronous batch jobs can't do asserts
        
    }
    
        //test to ensure that if the PC or the RVP are changed on a Territory Name, then the associated
    //Accounts have their Account Teams updated as well
        @isTest
    public static void afterupdateteamupdate(){
        Set<String> usernames = Utility.generateusernames(3);
        List<User> users = TestFactory.CreateUser(usernames);
        Map<String, String> userRoleMap = new Map<String, String>(); 
        userRoleMap.put(users[1].Id, 'Program Consultant');
        userRoleMap.put(users[2].Id, 'Regional VP');
        List<TerritoryName__c> territorynames = TestFactory.createTerritoryNames(5, users);
        List<String> zipcodes = Utility.generatezipcodes(5);
        List<Territory_ID__c> territories = TestFactory.createTerritories(zipCodes, territorynames);
        List<Account> accts = TestFactory.createSchoolAccounts(zipcodes);
        List<AccountTeamMember> atms = TestFactory.createAccountTeamMembers(accts[0].Id, userRoleMap);
        List<Contact> contacts = TestFactory.createContacts(accts);
        List<Opportunity> opps = TestFactory.createOpportunities(accts);
        
        Test.startTest();
        territorynames[0].Program_Consultant__c = users[0].Id;
        territorynames[0].Regional_VP__c = users[1].Id;
        update territorynames;
        Test.stopTest();
        
    }
}