force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_ID__c/Territory_ID__c.object-meta.xml
<CustomObject>
    <label>TerritoryID</label>
    <nameField>
        <label>TerritoryID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerritoryIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_ID__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</description>
    <inlineHelpText>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</inlineHelpText>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>TerritoryIDs</relationshipLabel>
    <relationshipName>TerritoryIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_ID__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <externalId>true</externalId>
    <label>Zip Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/TerritoryName__c.object-meta.xml
<CustomObject>
    <label>Territory Name</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryName__c/fields/Program_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Program_Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Regional Vice President assigned to this Territory. Added -03-2022 to consolidate Territory records</description>
    <inlineHelpText>The Regional Vice President assigned to this Territory</inlineHelpText>
    <label>Program Consultant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Names1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/fields/Regional_VP__c.field-meta.xml
<CustomField>
    <fullName>Regional_VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Regional Vice President assigned to this Territory. Added 03-2022 to consolidate Territory records</description>
    <inlineHelpText>The Regional Vice President assigned to this Territory</inlineHelpText>
    <label>Regional VP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Names</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TerritoryAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TerritoryID_w.cls
public class TerritoryID_w {
    /*Insert header snipper here
*/
    
    //declare class vars
    private string zip;
    private string amid;
    private string pcid;
    private string rvpid;
    public MAP<String, String> dmlResults = new Map<String, String>();
    Territory_ID__c theTerritoryID = new Territory_ID__c();
    
    //insert context
    public TerritoryID_w(Territory_ID__c tid, String triggercontext){
        this.theTerritoryID = tid;
        this.zip = tid.Zip_Code__c;
        if(triggercontext.contains('before')){
            //currently we have no processes that require a before context
        }
    }
    
    //update context
    public TerritoryID_w(Territory_ID__c oldTid, Territory_ID__c newTid, String triggercontext){
        this.theTerritoryID = newTid;
        this.zip = newTid.Zip_Code__c;
        if(triggercontext.contains('before')){
            //currently we do not need a before context
        } else if(triggercontext.contains('after')){
            //if the Territory ID record is reassigned to a new Territory Name
            //the Accounts and their Child objects need to inherit the attrituvtes of the new Territory Name
            if(theTerritoryID.Territory_Name__c != oldTid.Territory_Name__c){
                updateChildObjects();
            }
        }
    }
    
    private void updateChildObjects(){
        //call the Utility to do a master re-query of the TerritoryID record in the trigger
        //so we can get the attributes of the new Territory Name
        TerritoryID_u tidu = new TerritoryID_U(theTerritoryID);
        theTerritoryID = tidu.theTid;
        system.debug('the results of the TID U query are ' + theTerritoryID);
        Set<Id> tnIds = new Set<Id>();
        tnIds.add(theTerritoryID.Territory_Name__r.Id);
        String amId = theTerritoryID.Territory_Name__r.User__c;
        Map<String, String> userRoleMap = new Map<String, String>();
        userRoleMap.put('pcid', theTerritoryId.Territory_Name__r.Program_Consultant__c);
        userRoleMap.put('rvpid', theTerritoryId.Territory_Name__r.Regional_VP__c);
        
        //NOTE: DEPENDING ON PERFORMANCE THESE BATCH CALLS MAY NEED TO BE CHAINED TOGETHER
        //INSTEAD OF CALLED SEPARATELY
        
        //batch update accounts
        AccountsUpdateBatch batchacctupdate = new AccountsUpdateBatch(tnIds, amId);
        Database.executeBatch(batchacctupdate, 10);
        
        //batch update account teams
        AccountTeamMembersBatch batchatmupdate = new AccountTeamMembersBatch(tnIds, userRoleMap);
        Database.executeBatch(batchatmupdate, 10);
        
        //batch update contacts
        ContactsUpdateBatch batchconupdate = new ContactsUpdateBatch(tnIds, amId);
        Database.executeBatch(batchconupdate, 10);
        
        //batch update opps
        OpportunitiesUpdateBatch batchoppupdate = new OpportunitiesUpdateBatch(tnIds, amId);
        Database.executeBatch(batchoppupdate, 10);
        
    }
    
}