force-app/main/default/objects/Account/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <formula>Account.Territory_ID__c</formula>
    <label>Territory ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <formula>Account.Territory_Name__r.Name</formula>
    <label>Territory Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <formula>Account.Territory_ID__c</formula>
    <label>Territory ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <formula>Account.Territory_Name__r.Name</formula>
    <label>Territory Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory_ID__c/Territory_ID__c.object-meta.xml
<CustomObject>
    <label>TerritoryID</label>
    <nameField>
        <label>TerritoryID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerritoryIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_ID__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</description>
    <inlineHelpText>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</inlineHelpText>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>TerritoryIDs</relationshipLabel>
    <relationshipName>TerritoryIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryName__c/TerritoryName__c.object-meta.xml
<CustomObject>
    <label>Territory Name</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryName__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <label>Territory ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TerritoryID_t.cls
@isTest
public class TerritoryID_t {
    
    //Test to ensure that if the Territory Name related to the TerritoryID record is changed, then the 
    //Accounts, Account Teams, Contacts, and Opps are updated for the new Territory Assignments
    @isTest
    public static void afterupdate(){
        Set<String> usernames = Utility.generateusernames(3);
        List<User> users = TestFactory.CreateUser(usernames);
        List<TerritoryName__c> territorynames = TestFactory.createTerritoryNames(5, users);
        List<String> zipcodes = Utility.generatezipcodes(5);
        List<Territory_ID__c> territories = TestFactory.createTerritories(zipCodes, territorynames);
        List<Account> accts = TestFactory.createSchoolAccounts(zipcodes);
        List<Contact> contacts = TestFactory.createContacts(accts);
        List<Opportunity> opps = TestFactory.createOpportunities(accts);
        
        Test.startTest();
        territories[0].Territory_Name__c = territorynames[1].Id;
        update territories;
        Test.stopTest();
        
    }

}