force-app/main/default/objects/Lead/fields/AM__c.field-meta.xml
<CustomField>
    <fullName>AM__c</fullName>
    <label>AM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>Territory County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PC__c.field-meta.xml
<CustomField>
    <fullName>PC__c</fullName>
    <label>PC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RVP__c.field-meta.xml
<CustomField>
    <fullName>RVP__c</fullName>
    <label>RVP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Territory State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_ID__c/Territory_ID__c.object-meta.xml
<CustomObject>
    <label>TerritoryID</label>
    <nameField>
        <label>TerritoryID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerritoryIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_ID__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</description>
    <inlineHelpText>Lookup Relationship to the Territory Name. This allows us to Group TerritoryIDs/ZipCodes under Territories</inlineHelpText>
    <label>Territory Name</label>
    <referenceTo>TerritoryName__c</referenceTo>
    <relationshipLabel>TerritoryIDs</relationshipLabel>
    <relationshipName>TerritoryIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
public class LeadTriggerHandler {
    
    public static Boolean bypassTrigger = false;
    
    public LeadTriggerHandler() {}
    
    public void run() {
        if (bypassTrigger == true) {
            return;
        }
        
        if (Trigger.isBefore && Trigger.isInsert) {
            assignCustomTerritories(Trigger.new);
        }
        else if (Trigger.isBefore && Trigger.isUpdate) {
            assignCustomTerritories(Trigger.new);
        }
    }
    
    public static void assignCustomTerritories(List<Lead> leads) {
        Set<String> postalCodes = new Set<String>();
        for (Lead l: leads) {
            postalCodes.add(l.PostalCode);
        }
        TerritoryAssignmentHandler handler = new TerritoryAssignmentHandler(postalCodes, 'Lead', null);
        for (Lead l: leads) {
            TerritoryAssignmentHandler.TerritoryStruct territoryDetails = handler.getTerritoryDetails(l.Id, l.PostalCode, null);
            l.Territory_ID__c = territoryDetails.territoryNumber;
            l.Territory_Name__c = territoryDetails.territoryId;
            l.AM__c = territoryDetails.am;
            l.RVP__c = territoryDetails.rvp;
            l.PC__c = territoryDetails.pc;
            l.State__c = territoryDetails.state;
            l.County__c = territoryDetails.county;
            l.OwnerId = territoryDetails.amId != null ? territoryDetails.amId : l.OwnerId;
        }
    }
}